#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="arac_kiralama")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblArac(tblArac instance);
    partial void UpdatetblArac(tblArac instance);
    partial void DeletetblArac(tblArac instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Arac_Kiralama_Otomasyonu.Properties.Settings.Default.arac_kiralamaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblArac> tblAracs
		{
			get
			{
				return this.GetTable<tblArac>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblArac")]
	public partial class tblArac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _arac_no;
		
		private string _marka;
		
		private string _model;
		
		private string _plaka;
		
		private string _yakit_turu;
		
		private System.Nullable<int> _motor_gucu;
		
		private System.Nullable<int> _tork;
		
		private short _motor_hacmi;
		
		private string _renk;
		
		private string _vites;
		
		private System.Nullable<bool> _klima;
		
		private int _ruhsat_no;
		
		private bool _sigorta;
		
		private System.DateTime _muayne_bit_tar;
		
		private System.Nullable<decimal> _ucret;
		
		private System.Nullable<bool> _kiraDurumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onarac_noChanging(int value);
    partial void Onarac_noChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnplakaChanging(string value);
    partial void OnplakaChanged();
    partial void Onyakit_turuChanging(string value);
    partial void Onyakit_turuChanged();
    partial void Onmotor_gucuChanging(System.Nullable<int> value);
    partial void Onmotor_gucuChanged();
    partial void OntorkChanging(System.Nullable<int> value);
    partial void OntorkChanged();
    partial void Onmotor_hacmiChanging(short value);
    partial void Onmotor_hacmiChanged();
    partial void OnrenkChanging(string value);
    partial void OnrenkChanged();
    partial void OnvitesChanging(string value);
    partial void OnvitesChanged();
    partial void OnklimaChanging(System.Nullable<bool> value);
    partial void OnklimaChanged();
    partial void Onruhsat_noChanging(int value);
    partial void Onruhsat_noChanged();
    partial void OnsigortaChanging(bool value);
    partial void OnsigortaChanged();
    partial void Onmuayne_bit_tarChanging(System.DateTime value);
    partial void Onmuayne_bit_tarChanged();
    partial void OnucretChanging(System.Nullable<decimal> value);
    partial void OnucretChanged();
    partial void OnkiraDurumuChanging(System.Nullable<bool> value);
    partial void OnkiraDurumuChanged();
    #endregion
		
		public tblArac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arac_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int arac_no
		{
			get
			{
				return this._arac_no;
			}
			set
			{
				if ((this._arac_no != value))
				{
					this.Onarac_noChanging(value);
					this.SendPropertyChanging();
					this._arac_no = value;
					this.SendPropertyChanged("arac_no");
					this.Onarac_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plaka", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string plaka
		{
			get
			{
				return this._plaka;
			}
			set
			{
				if ((this._plaka != value))
				{
					this.OnplakaChanging(value);
					this.SendPropertyChanging();
					this._plaka = value;
					this.SendPropertyChanged("plaka");
					this.OnplakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yakit_turu", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string yakit_turu
		{
			get
			{
				return this._yakit_turu;
			}
			set
			{
				if ((this._yakit_turu != value))
				{
					this.Onyakit_turuChanging(value);
					this.SendPropertyChanging();
					this._yakit_turu = value;
					this.SendPropertyChanged("yakit_turu");
					this.Onyakit_turuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motor_gucu", DbType="Int")]
		public System.Nullable<int> motor_gucu
		{
			get
			{
				return this._motor_gucu;
			}
			set
			{
				if ((this._motor_gucu != value))
				{
					this.Onmotor_gucuChanging(value);
					this.SendPropertyChanging();
					this._motor_gucu = value;
					this.SendPropertyChanged("motor_gucu");
					this.Onmotor_gucuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tork", DbType="Int")]
		public System.Nullable<int> tork
		{
			get
			{
				return this._tork;
			}
			set
			{
				if ((this._tork != value))
				{
					this.OntorkChanging(value);
					this.SendPropertyChanging();
					this._tork = value;
					this.SendPropertyChanged("tork");
					this.OntorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motor_hacmi", DbType="SmallInt NOT NULL")]
		public short motor_hacmi
		{
			get
			{
				return this._motor_hacmi;
			}
			set
			{
				if ((this._motor_hacmi != value))
				{
					this.Onmotor_hacmiChanging(value);
					this.SendPropertyChanging();
					this._motor_hacmi = value;
					this.SendPropertyChanged("motor_hacmi");
					this.Onmotor_hacmiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renk", DbType="VarChar(20)")]
		public string renk
		{
			get
			{
				return this._renk;
			}
			set
			{
				if ((this._renk != value))
				{
					this.OnrenkChanging(value);
					this.SendPropertyChanging();
					this._renk = value;
					this.SendPropertyChanged("renk");
					this.OnrenkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vites", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string vites
		{
			get
			{
				return this._vites;
			}
			set
			{
				if ((this._vites != value))
				{
					this.OnvitesChanging(value);
					this.SendPropertyChanging();
					this._vites = value;
					this.SendPropertyChanged("vites");
					this.OnvitesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klima", DbType="Bit")]
		public System.Nullable<bool> klima
		{
			get
			{
				return this._klima;
			}
			set
			{
				if ((this._klima != value))
				{
					this.OnklimaChanging(value);
					this.SendPropertyChanging();
					this._klima = value;
					this.SendPropertyChanged("klima");
					this.OnklimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruhsat_no", DbType="Int NOT NULL")]
		public int ruhsat_no
		{
			get
			{
				return this._ruhsat_no;
			}
			set
			{
				if ((this._ruhsat_no != value))
				{
					this.Onruhsat_noChanging(value);
					this.SendPropertyChanging();
					this._ruhsat_no = value;
					this.SendPropertyChanged("ruhsat_no");
					this.Onruhsat_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigorta", DbType="Bit NOT NULL")]
		public bool sigorta
		{
			get
			{
				return this._sigorta;
			}
			set
			{
				if ((this._sigorta != value))
				{
					this.OnsigortaChanging(value);
					this.SendPropertyChanging();
					this._sigorta = value;
					this.SendPropertyChanged("sigorta");
					this.OnsigortaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_muayne_bit_tar", DbType="Date NOT NULL")]
		public System.DateTime muayne_bit_tar
		{
			get
			{
				return this._muayne_bit_tar;
			}
			set
			{
				if ((this._muayne_bit_tar != value))
				{
					this.Onmuayne_bit_tarChanging(value);
					this.SendPropertyChanging();
					this._muayne_bit_tar = value;
					this.SendPropertyChanged("muayne_bit_tar");
					this.Onmuayne_bit_tarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucret", DbType="Money")]
		public System.Nullable<decimal> ucret
		{
			get
			{
				return this._ucret;
			}
			set
			{
				if ((this._ucret != value))
				{
					this.OnucretChanging(value);
					this.SendPropertyChanging();
					this._ucret = value;
					this.SendPropertyChanged("ucret");
					this.OnucretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiraDurumu", DbType="Bit")]
		public System.Nullable<bool> kiraDurumu
		{
			get
			{
				return this._kiraDurumu;
			}
			set
			{
				if ((this._kiraDurumu != value))
				{
					this.OnkiraDurumuChanging(value);
					this.SendPropertyChanging();
					this._kiraDurumu = value;
					this.SendPropertyChanged("kiraDurumu");
					this.OnkiraDurumuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
